# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHeycZxpZR2nz1taeslYP_c_ZYGVuJ-s
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

fashion_mnist = keras.datasets.fashion_mnist

(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

x_train,x_test = x_train / 255.0 , x_test / 255.0

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28,1)),
    keras.layers.Dense(128,activation = 'relu'),
    keras.layers.Dense(10,activation = 'softmax')
])

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

history = model.fit(x_train,y_train,validation_split = 0.1,epochs=10)

import matplotlib.pyplot as plt
plt.imshow(x_train[2000])

plt.imshow(x_test[2000])

import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))

for i in range(20):
    plt.subplot(4, 5, i+1)
    plt.imshow(x_train[i])
    plt.xticks([])
    plt.yticks([])
    plt.tight_layout()

plt.show()

model=models.Sequential()
model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(128,activation ='relu'))
model.add(layers.Dense(10,activation = 'sigmoid'))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('accuracy')
plt.xlabel('accuracy')
plt.ylabel('val_accuracy')
plt.legend(['accuracy','val_accuracy'])
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('accuracy')
plt.xlabel('accuracy')
plt.ylabel('val_accuracy')
plt.show()

history1=model.fit(x_test,y_test,validation_data=(x_test,y_test),epochs=10)

test_loss, test_accuracy = model.evaluate(x_test, y_test)

test_image = x_test[567]
actual_label = y_test[567]
predictions=model.predict(x_test)
pred_probs = predictions[567]
predicted_label = np.argmax(pred_probs)
confidence = pred_probs[predicted_label]
plt.figure(figsize=(10, 6))
plt.imshow(test_image, cmap='gray')
plt.text(0.5,-1,f"Actual: {class_names[actual_label]} (Class {actual_label})")
plt.text(0.5,-3,f"Predicted: {class_names[predicted_label]} (Class {predicted_label})\n")

